'use client';
import {useEffect,useRef,useState} from 'react';
import {Pencil, Plus, Search, Wallet, BriefcaseBusiness, Heart, X, ExternalLink, Check, Loader2, ArrowLeft, Menu, Coins, LogOut} from 'lucide-react';
import {Paint} from './paint';
import {CoinPageStudio} from './coin-page-studio';
import {emptyDrawing,renderDrawing,validateEffort,type Drawing} from '@/lib/drawing';
import {type Coin, type Job, type Config, type Submission} from '@/lib/types';
type Provider={publicKey?:{toBase58():string};connect():Promise<{publicKey:{toBase58():string}}> ;disconnect():Promise<void>;signMessage(message:Uint8Array,encoding?:string):Promise<{signature:Uint8Array}>;signTransaction(transaction:unknown):Promise<any>;on?(event:string,cb:(key:any)=>void):void;removeListener?(event:string,cb:(key:any)=>void):void};
declare global {interface Window {phantom?:{solana?:Provider};solflare?:Provider;solana?:Provider}}
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Something went wrong. Please try again.');return d}
const short=(s:string)=>s?`${s.slice(0,4)}…${s.slice(-4)}`:'a little guy';
function Art({coin,className=''}:{coin:Coin;className?:string}){return coin.image?<img className={'coin-art '+className} src={coin.image} alt={coin.name}/>:<div className="blank-art"><Pencil size={38}/><span>a blank page, for now.</span></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current!;d.showModal();const listener=(e:Event)=>{e.preventDefault();close()};d.addEventListener('cancel',listener);return()=>{d.removeEventListener('cancel',listener);d.close()}},[]);return <dialog ref={ref} className="modal" onClick={e=>{if(e.target===ref.current)close()}}><div className="modal-top"><h2>{title}</h2><button className="icon-btn" onClick={close} aria-label="Close dialog"><X/></button></div>{children}</dialog>}
export default function Doodle({initialCoinId}:{initialCoinId?:string}){
 const [coinLoading,setCoinLoading]=useState(!!initialCoinId),[coinError,setCoinError]=useState('');
 const [focusSetup,setFocusSetup]=useState(false);
 const [launchReview,setLaunchReview]=useState<any>(null);
 const resumeLaunch=useRef(false);
 const [pending,setPending]=useState<{kind:string;id:string;transaction?:number[]}|null>(null);
 const [view,setView]=useState(initialCoinId?'coin':'explore'),[coins,setCoins]=useState<Coin[]>([]),[jobs,setJobs]=useState<Job[]>([]),[config,setConfig]=useState<Config|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('live'),[selected,setSelected]=useState<Coin|null>(null),[wallet,setWallet]=useState(''),[walletModal,setWalletModal]=useState(false),[info,setInfo]=useState(false),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[jobModal,setJobModal]=useState(false),[activeJob,setActiveJob]=useState<Job|null>(null),[mobileNav,setMobileNav]=useState(false);
 const provider=useRef<Provider|null>(null);const [drawing,setDrawing]=useState<Drawing>(emptyDrawing),[name,setName]=useState(''),[symbol,setSymbol]=useState(''),[description,setDescription]=useState(''),[saved,setSaved]=useState<Coin|null>(null);
 const refresh=async()=>{try{const d=await api('coins');setCoins(d.coins);const j=await api('jobs');setJobs(j.jobs);setLoadError('')}catch(e){setLoadError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{refresh();api('config').then(setConfig).catch(()=>setLoadError('Launch settings are unavailable. Please refresh.'))},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const p=provider.current;if(!p)return;const changed=()=>{setWallet('');provider.current=null;api('auth/logout',{}).catch(()=>{})};p.on?.('accountChanged',changed);p.on?.('disconnect',changed);return()=>{p.removeListener?.('accountChanged',changed);p.removeListener?.('disconnect',changed)}},[wallet]);
 const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');try{await fn()}catch(e){setError((e as Error).message||'Request cancelled. Your work is still here.')}finally{setBusy('')}};
 const connect=async(kind:string)=>run('Connecting',async()=>{const p=kind==='Phantom'?(window.phantom?.solana||window.solana):window.solflare;if(!p)throw new Error(`Open http://127.0.0.1:5173 in your regular browser with the ${kind} extension, then connect there.`);const result=await p.connect(),address=result.publicKey.toBase58(),challenge=await api('auth/challenge',{address});const signature=await p.signMessage(new TextEncoder().encode(challenge.message),'utf8');await api('auth/verify',{address,nonce:challenge.nonce,signature:Array.from(signature.signature)});provider.current=p;setWallet(address);setWalletModal(false);setNotice('You’re in. Make something weird.')});
 const go=(next:string)=>{window.history.pushState({},'','/');setView(next);setSelected(null);setMobileNav(false);setError('');window.scrollTo({top:0,behavior:'smooth'})};
 useEffect(()=>{if(!focusSetup||view!=='create')return;const frame=requestAnimationFrame(()=>{const form=document.getElementById('launch-setup');form?.scrollIntoView({behavior:'smooth',block:'start'});form?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true});setFocusSetup(false)});return()=>cancelAnimationFrame(frame)},[view,focusSetup]);
 const finishDrawing=(completed:Drawing)=>{try{validateEffort(completed,renderDrawing(completed));setDrawing(completed);setSaved(null);setError('');setView('create');setSelected(null);setFocusSetup(true)}catch(e){setError((e as Error).message)}};
 const prepareLaunch=async(coin:Coin)=>{const prepared=await api('launch/prepare',{coinId:coin.id});if(prepared.signature){setPending({kind:'launch',id:prepared.intentId});const confirmed=await api('launch/confirm',{intentId:prepared.intentId});setSelected(confirmed.coin);setSaved(confirmed.coin);setPending(null);localStorage.removeItem('doodle-pending-launch');openCoin(confirmed.coin);await refresh();return}setLaunchReview(prepared)};
 const launch=async(coin:Coin)=>{if(!wallet){setWalletModal(true);return}await run('Checking mainnet launch',()=>prepareLaunch(coin))};
 const launchDrawing=async()=>{if(!wallet){resumeLaunch.current=true;setWalletModal(true);return}await run('Getting your coin ready',async()=>{if(pending)throw new Error('Check your pending transaction receipt first.');if(!name.trim()||!symbol.trim())throw new Error('Your little guy needs a name and ticker.');validateEffort(drawing,renderDrawing(drawing));let coin=saved;if(!coin){const asset=await api('drawings',{drawing});const d=await api('coins',{name,symbol,description,pair:'SOL',communityBps:0,image:asset.url});coin=d.coin;setSaved(coin);await refresh()}if(coin!.status==='live'){openCoin(coin!);return}await prepareLaunch(coin!)})};
 useEffect(()=>{if(wallet&&resumeLaunch.current){resumeLaunch.current=false;void launchDrawing()}},[wallet]);
 const approveLaunch=async()=>{const prepared=launchReview;if(!prepared)return;await run('Approve in your wallet',async()=>{if(!provider.current)throw new Error('Connect your wallet first.');if(prepared.network!=='mainnet-beta'||prepared.launch.creator!==wallet)throw new Error('Reconnect the creator wallet and prepare a fresh launch.');const {Transaction}=await import('@solana/web3.js');const tx=Transaction.from(Uint8Array.from(atob(prepared.transaction),c=>c.charCodeAt(0)));const signed=await provider.current.signTransaction(tx);const receipt={kind:'launch',id:prepared.intentId,transaction:Array.from(signed.serialize() as Uint8Array)};localStorage.setItem('doodle-pending-launch',JSON.stringify(receipt));setPending(receipt);setLaunchReview(null);await api('launch/submit',{intentId:prepared.intentId,transaction:Array.from(signed.serialize() as Uint8Array)});const confirmed=await api('launch/confirm',{intentId:prepared.intentId});setSaved(confirmed.coin);setSelected(confirmed.coin);setPending(null);localStorage.removeItem('doodle-pending-launch');setNotice('Your coin is live on Solana mainnet.');openCoin(confirmed.coin);await refresh()})};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('doodle-pending-launch')||'null');if(saved?.kind==='launch'&&typeof saved.id==='string')setPending(saved)}catch{}},[]);

 const openCoin=(c:Coin)=>{window.history.pushState({},'',`/coin/${c.id}`);setSelected(c);setView('coin');setCoinError('');setCoinLoading(false);setError('');window.scrollTo({top:0,behavior:'smooth'})};
 useEffect(()=>{let request=0;const sync=async()=>{const current=++request;const match=window.location.pathname.match(/^\/coin\/([^/]+)\/?$/);setSelected(null);setCoinError('');if(!match){setCoinLoading(false);setView('explore');return}setView('coin');setCoinLoading(true);try{const d=await api('coins/'+encodeURIComponent(match[1]));if(current===request)setSelected(d.coin)}catch(e){if(current===request)setCoinError((e as Error).message)}finally{if(current===request)setCoinLoading(false)}};sync();window.addEventListener('popstate',sync);return()=>{request++;window.removeEventListener('popstate',sync)}},[]);
 const openJob=async(j:Job)=>{setActiveJob(j);if(j.owner===wallet)await run('Loading submissions',async()=>{const d=await api(`jobs/${j.id}`);setActiveJob(d.job)})};
 const payout=async(j:Job,s:Submission)=>run('Preparing reward',async()=>{if(!provider.current)throw new Error('Connect your wallet first.');const {transaction,intentId,signature}=await api('payout/prepare',{jobId:j.id,submissionId:s.id});if(signature){await api('payout/confirm',{intentId});setActiveJob(null);await refresh();return;}const {Transaction}=await import('@solana/web3.js');const tx=Transaction.from(Uint8Array.from(atob(transaction),c=>c.charCodeAt(0)));const signed=await provider.current.signTransaction(tx);setPending({kind:'payout',id:intentId});await api('payout/submit',{intentId,transaction:Array.from(signed.serialize() as Uint8Array)});await api('payout/confirm',{intentId});setNotice('Reward confirmed on Solana. Good job. Actual money.');setActiveJob(null);setPending(null);await refresh()});
 const filtered=coins.filter(c=>(filter==='all'||filter==='mine'&&c.owner===wallet||filter==='live'&&c.status==='live'||filter==='draft'&&c.status==='draft')&&`${c.name} ${c.symbol}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><header className="site-header"><button className="brand" onClick={()=>go('explore')} aria-label="Doodle home">d<span className="brand-eyes">oo</span>dle<span className="brand-star">✳</span></button><nav className={mobileNav?'open':''} aria-label="Main navigation"><button className={view==='explore'||view==='coin'?'active':''} onClick={()=>go('explore')}>the playground</button><button onClick={()=>setInfo(true)}>how it works</button></nav><div className="header-actions"><span className="chain-label">≋ solana</span><button className="wallet-button" onClick={()=>wallet?run('Disconnecting',async()=>{await api('auth/logout',{});await provider.current?.disconnect();provider.current=null;setWallet('')}):setWalletModal(true)}>{wallet?<LogOut size={16}/>:<Wallet size={16}/>}<span>{wallet?short(wallet):'connect wallet'}</span></button><button className="mobile-menu icon-btn" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle menu"><Menu/></button></div></header>
 <div className="announcement"><span className="scribble-star">✳</span> a launchpad for artists, by an artist. <span className="announcement-end">your hand. your effort. your coin.</span></div>
 <main>{pending&&<div className="info-box pending-box"><span>A transaction needs confirmation. Retry this operation before starting another.</span><button className="small-button" disabled={!!busy} onClick={()=>run("Checking receipt",async()=>{if(pending.transaction)await api(`${pending.kind}/submit`,{intentId:pending.id,transaction:pending.transaction});const result=await api(`${pending.kind}/confirm`,{intentId:pending.id});if(result.coin){setSaved(result.coin);setSelected(result.coin)}setPending(null);localStorage.removeItem("doodle-pending-launch");setActiveJob(null);setNotice("Transaction confirmed.");await refresh()})}>check receipt</button></div>}
 {view==='explore'&&<><section className="intro"><div><div className="eyebrow"><span className="tag-dot"/> LESS SLOP. MORE SOUL.</div><h1>good coins start<br/>with <span className="underline-word">bad drawings.</span></h1><p>Before Pepe was a ticker, he was an artist’s drawing.<br/>The next little guy starts with your hand.</p><div className="intro-actions"><button className="primary" onClick={()=>go('create')}><Pencil size={19}/> draw & launch a coin</button><span className="hand-note">yes, even your drawing.</span></div></div><div className="hero-studio"><Paint onDone={finishDrawing} initial={drawing} onChange={setDrawing}/><span className="hand">go on. draw the first line.</span></div></section>
 <section className="principle-strip"><span><Pencil size={20}/><b>drawn here.</b> no image uploads.</span><span><Heart size={20}/><b>made by you.</b> creator fees stay yours.</span><button onClick={()=>setInfo(true)}>a little different <Plus size={17}/></button></section>
 <section className="playground"><div className="section-heading"><div><h2>the playground <span className="hand small">every legend starts somewhere.</span></h2></div><button className="small-button" onClick={()=>go('create')}><Plus size={16}/> new little guy</button></div><div className="explore-controls"><div className="filter-tabs">{[['live','launched here'],['all','all little guys'],['draft','in the sketchbook'],['mine','my guys']].map(([id,label])=><button key={id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><label className="search"><Search size={17}/><input placeholder="find a little guy…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search coins"/></label></div>
 {loadError&&<div className="inline-error">{loadError} <button onClick={refresh}>Retry</button></div>}{loading?<div className="empty"><Loader2 className="spin"/> fetching the little guys…</div>:filtered.length>0?<div className="coin-grid">{filtered.map(c=><CoinCard key={c.id} coin={c} click={()=>openCoin(c)}/>)}</div>:<div className="empty compact"><Pencil size={23}/><div><b>{query?'No little guys by that name.':filter==='mine'&&!wallet?'Connect your wallet to find your guys.':filter==='live'?'No launches here yet.':'A fresh page. Literally.'}</b><p>{query?'Try another name or ticker.':filter==='live'?'Launched coins will appear here with their names and their own pages. Browse the sketchbook to see saved characters.':'Be the first to put your character in the clubhouse.'}</p></div>{!query&&<button className="text-button" onClick={()=>go('create')}>make one</button>}</div>}
 
 </section><section className="artist-note"><span className="eyebrow">A NOTE FROM THE ARTIST BEHIND DOODLE</span><h2>before the ticker, there was a drawing.</h2><p>Pepe began as a character in Matt Furie’s comic. An artist made a funny little frog, and the internet gave him a life of his own. That handmade spirit is what we want more of onchain.</p><p>“I’m an artist. I want more creativity in this space — more characters with personality, more people putting real effort into their projects. Not another thousand generated images attached to a ticker.”</p><p>Let’s bring that energy back. Make a weird little character. Give it a name, a story, something people can care about. Here, you draw your coin from a blank canvas. No image uploads. No AI generation button. Just your hand, a little effort, and an idea.</p><span className="hand">made by an artist. for the people who make things.</span></section><section className="club-banner"><div><span className="eyebrow">BACK TO THE LITTLE GUYS</span><h2>draw it. name it.<br/>let it loose.</h2><p>A character, a ticker, and a SOL pair.<br/>You create the coin. You keep the creator fees.</p><button className="dark-button" onClick={()=>go('create')}><Pencil size={18}/> make something weird</button></div><div className="note-paper"><span>the original recipe</span><b>ONE LITTLE GUY.</b><p>drawn by you.<br/>paired with SOL.<br/>creator fees for the creator.</p></div></section></>}
 {view==='create'&&<><button className="back-link" onClick={()=>go('explore')}><ArrowLeft size={17}/> back to the playground</button><div className="create-heading"><div className="eyebrow">YOUR HAND IS THE LAUNCH BUTTON</div><h1>make a little guy.</h1><p>Pepe had a face. WIF had a hat. Yours starts with a blank canvas.</p></div><div className="create-layout"><section><Paint onDone={finishDrawing} initial={drawing} onChange={v=>{setDrawing(v);setSaved(null)}}/><div className="drawing-rule"><Pencil size={18}/><div><b>Drawn here. Not uploaded.</b><p>Your coin’s artwork is made from the strokes you draw on this canvas. No importing, pasting images, or generating a PFP. A mouse, finger, or stylus is all you need.</p></div></div></section><section className="launch-form" id="launch-setup"><div className="step-label"><span>01</span> give them an identity</div><div className="field-row"><label>name<input maxLength={32} value={name} onChange={e=>{setName(e.target.value);setSaved(null)}} placeholder="e.g. greg"/></label><label className="ticker-label">ticker<input maxLength={10} value={symbol} onChange={e=>{setSymbol(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));setSaved(null)}} placeholder="GREG"/></label></div><label>their entire personality<textarea rows={3} maxLength={280} value={description} onChange={e=>{setDescription(e.target.value);setSaved(null)}} placeholder="he is just a frog with a pencil. please be nice to him."/><span className="field-help">{description.length}/280 · a sentence is a perfectly good whitepaper.</span></label><div className="form-divider"/><div className="step-label"><span>02</span> keep it simple</div><div className="info-box"><b>≋ Paired with SOL</b><p>Every coin launches against SOL. Creator fees belong to the wallet that launches it.</p></div><p className="field-help">You keep 100% of the creator-fee portion. Network and protocol fees still apply.</p><button className="primary full" disabled={!!busy||!!pending} onClick={launchDrawing}>{busy?<Loader2 size={18} className="spin"/>:<Pencil size={18}/>} {busy||(!wallet?'connect wallet & launch':saved?.status==='live'?'open my coin':'launch my coin')}</button><p className="under-button">We save your drawing and upload the art for you. Review the cost, then approve in your wallet.</p>{error&&<p className="inline-error" role="alert">{error}</p>}{saved&&saved.status!=='live'&&<p className="field-help">Your drawing is saved. Retrying uses this same little guy.</p>}</section></div></>}

 {view==='coin'&&coinLoading&&<div className="empty">opening this little guy’s page…</div>}{view==='coin'&&coinError&&<div className="empty" role="alert"><h2>{coinError}</h2><button className="small-button" onClick={()=>go('explore')}>back to the playground</button></div>}{view==='coin'&&selected&&<><button className="back-link" onClick={()=>go('explore')}><ArrowLeft size={17}/> back to the playground</button><div className="coin-detail"><div className="portrait"><Art coin={selected}/><span className="portrait-caption">{selected.example!==undefined?'an imaginary friend.':'certified little guy.'}</span></div><div><span className="pill">{selected.status==='example'?'character example':selected.status==='live'?'launched':'in the sketchbook'}</span><h1>{selected.name}</h1><span className="coin-symbol">${selected.symbol} <span> / {selected.pair}</span></span><p className="detail-description">{selected.description||'A mysterious little guy.'}</p><div className="detail-stats"><div><small>pair</small><b>SOL</b></div><div><small>creator</small><b>{selected.owner?short(selected.owner):'imaginary'}</b></div><div><small>network</small><b>Solana</b></div></div>{selected.example!==undefined?<div className="info-box">This is an example character, not a launched token. Make your own little guy to start a real clubhouse.</div>:<div className="info-box">{selected.status==='live'?'On-chain launch confirmed.':'Saved character. No token has been minted.'}</div>}<div className="detail-actions">{selected.example!==undefined?<button className="primary" onClick={()=>go('create')}><Pencil size={18}/> make my own little guy</button>:selected.owner===wallet?<>{selected.status!=='live'&&<button className="small-button" disabled={!config?.launchEnabled||!!busy} onClick={()=>launch(selected)}>launch coin</button>}</>:null}{selected.mint&&<a className="primary" href={`https://pump.fun/coin/${selected.mint}`} target="_blank" rel="noreferrer">trade on Pump <ExternalLink size={16}/></a>}{selected.mint&&<a className="small-button" target="_blank" rel="noreferrer" href={`https://explorer.solana.com/address/${selected.mint}${config?.network==='devnet'?'?cluster=devnet':''}`}>view token <ExternalLink size={16}/></a>}</div>{selected.owner===wallet&&!config?.launchEnabled&&<p className="field-help">{config?.launchReason}</p>}</div></div><CoinPageStudio key={selected.id} coinId={selected.id} isOwner={!!wallet&&selected.owner===wallet}/></>}
 </main><footer><span className="footer-logo">doodle✳</span><span>for artists, by an artist. no shortcuts to a little guy.</span><button onClick={()=>setInfo(true)}>made for the people who make things.</button><small>Solana · {config?.network||'loading network'} · early build</small></footer>
 {notice&&<div className="toast" role="status"><Check size={20}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={17}/></button></div>}{error&&<div className="error-toast" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
 {launchReview&&<Modal title="one last look. real SOL." close={()=>{if(!busy)setLaunchReview(null)}}><h3>{launchReview.launch.name} (${launchReview.launch.symbol})</h3><p>Launch on Solana mainnet through Pump, paired with SOL.</p><p><b>Estimated cost:</b> {(launchReview.launch.estimatedCostLamports/1e9).toFixed(6)} SOL, including account rent and network fees.</p><p><b>Creator fees:</b> your wallet ({short(launchReview.launch.creator)}). No initial token purchase.</p><p className="field-help">Your drawing and metadata will be public on IPFS. The launch creates a real token. Check the transaction in your wallet.</p><button className="primary full" disabled={!!busy} onClick={approveLaunch}>{busy||'approve launch in wallet'}</button>{error&&<p role="alert" className="inline-error">{error}</p>}</Modal>}
 {walletModal&&<Modal title="come on in." close={()=>{resumeLaunch.current=false;setWalletModal(false)}}><p>Connect your Solana wallet and sign a free message to prove it’s yours. Signing in does not move funds.</p><div className="wallet-options">{['Phantom','Solflare'].map(w=><button className="small-button" disabled={!!busy} key={w} onClick={()=>connect(w)}><Wallet/>{w}{busy&&<Loader2 className="spin" size={16}/>}</button>)}</div><p className="field-help">On desktop, open http://127.0.0.1:5173 in Chrome or Brave with your wallet extension. This in-app preview may not expose extensions. Never share your seed phrase.</p>{error&&<p className="inline-error">{error}</p>}</Modal>}
 {info&&<Modal title="little guys. original spirit." close={()=>setInfo(false)}><div className="how-step"><span>1</span><div><h3>Draw your little guy.</h3><p>Your hand, a blank canvas, and an idea. Every coin image is drawn here.</p></div></div><div className="how-step"><span>2</span><div><h3>Launch against SOL.</h3><p>Give it a name and ticker. Approve the launch with your Solana wallet.</p></div></div><div className="how-step"><span>3</span><div><h3>Your character. Your creator fees.</h3><p>The launching dev keeps the creator-fee portion. Make the coin page your own with stories and drawings.</p></div></div><div className="info-box">Drawing, saved characters, and custom pages are ready. {config?.launchReason}</div></Modal>}
 {jobModal&&selected&&<Modal title="give your guy a helping hand." close={()=>setJobModal(false)}><form onSubmit={e=>{e.preventDefault();if(!wallet){setWalletModal(true);return}const f=new FormData(e.currentTarget);run('Posting job',async()=>{await api('jobs',{coinId:selected.id,title:f.get('title'),description:f.get('description'),reward:f.get('reward')});setJobModal(false);setNotice('Job posted. Let the useful nonsense begin.');await refresh()})}}><label>the job<input name="title" required maxLength={80} placeholder="Draw greg getting his first paycheck"/></label><label>what does finished look like?<textarea name="description" required maxLength={1200} rows={4} placeholder="A transparent PNG sticker pack, 6 poses, 512px minimum…"/></label><label>reward in SOL<input name="reward" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,9})?" placeholder="0.1"/></label><p className="field-help">This is your payment pledge, not an escrow deposit. Payment comes from your connected wallet after you approve work.</p><button className="primary full" disabled={!!busy}>post job</button></form>{error&&<p className="inline-error">{error}</p>}</Modal>}
 {activeJob&&<Modal title={activeJob.title} close={()=>setActiveJob(null)}><span className="pill">{activeJob.status}</span><p>{activeJob.description}</p><div className="reward-box"><span>creator-funded reward</span><b>{activeJob.reward} SOL</b></div>{activeJob.owner===wallet?<><h3>submissions</h3>{!activeJob.submissions?.length&&<p className="muted">No work submitted yet.</p>}{activeJob.submissions?.map(s=><div className="submission" key={s.id}><b>{short(s.wallet)}</b><p>{s.note}</p><a href={s.url} target="_blank" rel="noopener noreferrer">view work <ExternalLink size={14}/></a><span className="pill">{s.status}</span>{['open','paying'].includes(activeJob.status)&&s.status==='submitted'&&<button className="small-button" disabled={!!busy} onClick={()=>payout(activeJob,s)}>approve & pay {activeJob.reward} SOL</button>}{s.signature&&<a href={`https://explorer.solana.com/tx/${s.signature}${config?.network==='devnet'?'?cluster=devnet':''}`} target="_blank" rel="noreferrer">payment receipt</a>}</div>)}</>:activeJob.status==='open'?<form onSubmit={e=>{e.preventDefault();if(!wallet){setWalletModal(true);return}const f=new FormData(e.currentTarget);run('Submitting your work',async()=>{await api(`jobs/${activeJob.id}/submit`,{url:f.get('url'),note:f.get('note')});setActiveJob(null);setNotice('Work submitted. The creator can now review it.')})}}><label>link to your work<input name="url" type="url" required placeholder="https://…"/></label><label>a little context<textarea name="note" maxLength={1000} required rows={3} placeholder="Here’s what I made…"/></label><p className="field-help">Submission does not guarantee payment. The creator chooses one completed submission for this job.</p><button className="primary full" disabled={!!busy}>{wallet?'submit my work':'connect to submit'}</button></form>:<p>This job has been completed.</p>}{error&&<p className="inline-error">{error}</p>}</Modal>}
 </div>
}
function CoinCard({coin,click}:{coin:Coin;click:()=>void}){return <a className="coin-card" href={`/coin/${coin.id}`} onClick={e=>{if(e.button===0&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();click()}}}><div className={`card-art color-${coin.example??2}`}><Art coin={coin}/><span className="card-badge">{coin.example!==undefined?'example':coin.status==='live'?'launched':'sketchbook'}</span></div><div className="card-content"><div className="card-name"><h3>{coin.name}</h3><span>${coin.symbol}</span></div><p>{coin.description||'A little guy with a big blank page.'}</p><div className="card-bottom"><span><Pencil size={14}/> hand drawn</span><span>{coin.pair}</span></div></div></a>}


