'use client';
import {useEffect,useRef,useState} from 'react';
import {Pencil,Eraser,Undo2,Redo2,Trash2,Download,PaintBucket,Check} from 'lucide-react';
import {emptyDrawing,renderDrawing,type Drawing,type Stroke} from '@/lib/drawing';
const colors=['#242323','#ffffff','#8ccf6e','#ffc94d','#f58cb2','#77c7ee','#b09beb','#ef7251','#946340'];
export function Paint({onChange,onDone,initial,doneLabel='done drawing — launch setup',doneHint='next: name your little guy.'}:{onChange:(drawing:Drawing)=>void;onDone:(drawing:Drawing)=>void;initial?:Drawing;doneLabel?:string;doneHint?:string}){
 const canvas=useRef<HTMLCanvasElement>(null),active=useRef<Stroke|null>(null),strokes=useRef<Stroke[]>(initial?.strokes||[]),redo=useRef<Stroke[]>([]);
 const [color,setColor]=useState(colors[0]),[size,setSize]=useState(7),[tool,setTool]=useState<Stroke['tool']>('pen'),[revision,setRevision]=useState(0);
 const redraw=()=>{const pixels=renderDrawing({version:1,strokes:strokes.current});const image=new ImageData(640,640);image.data.set(pixels);canvas.current!.getContext('2d')!.putImageData(image,0,0)};
 const save=()=>{redraw();onChange({version:1,strokes:[...strokes.current]});setRevision(v=>v+1)};
 useEffect(()=>{redraw()},[]);
 const point=(e:React.PointerEvent):[number,number]=>{const r=canvas.current!.getBoundingClientRect();return [Math.max(0,Math.min(639,Math.round((e.clientX-r.left)*640/r.width))),Math.max(0,Math.min(639,Math.round((e.clientY-r.top)*640/r.height)))]};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{e.preventDefault();if(strokes.current.length>=250)return;canvas.current!.setPointerCapture(e.pointerId);active.current={tool,color,size,points:[point(e)]};const x=canvas.current!.getContext('2d')!;x.strokeStyle=tool==='eraser'?'#ffffff':color;x.fillStyle=x.strokeStyle;x.lineWidth=size;x.lineCap='round';x.lineJoin='round';const[a,b]=point(e);x.beginPath();x.arc(a,b,size/2,0,Math.PI*2);if(tool!=='fill')x.fill();x.beginPath();x.moveTo(a,b);if(tool==='fill')stop()};
 const move=(e:React.PointerEvent)=>{const s=active.current;if(!s||s.points.length>=3000)return;const p=point(e),last=s.points[s.points.length-1];if(Math.hypot(p[0]-last[0],p[1]-last[1])<2)return;s.points.push(p);const x=canvas.current!.getContext('2d')!;x.lineTo(...p);x.stroke()};
 const stop=()=>{if(!active.current)return;strokes.current.push(active.current);active.current=null;redo.current=[];save()};
 const penCount=strokes.current.filter(s=>s.tool==='pen').length;
 return <div className="paint-window" data-revision={revision}><div className="window-title"><span><span className="window-dot"/> your_little_guy — draw it yourself</span><span>▁ □ ×</span></div><div className="paint-body"><div className="tool-rail">{([[Pencil,'pen','Pencil'],[PaintBucket,'fill','Fill'],[Eraser,'eraser','Eraser']] as const).map(([Icon,id,label])=><button key={id} type="button" className={tool===id?'selected':''} aria-label={label} title={label} onClick={()=>setTool(id)}><Icon size={20}/></button>)}<div className="rail-line"/><button type="button" aria-label="Undo" disabled={!strokes.current.length} onClick={()=>{const s=strokes.current.pop();if(s)redo.current.push(s);save()}}><Undo2 size={19}/></button><button type="button" aria-label="Redo" disabled={!redo.current.length} onClick={()=>{const s=redo.current.pop();if(s)strokes.current.push(s);save()}}><Redo2 size={19}/></button><button type="button" aria-label="Clear canvas" onClick={()=>{strokes.current=[];redo.current=[];save()}}><Trash2 size={19}/></button><button type="button" aria-label="Download drawing" onClick={()=>{const a=document.createElement('a');a.download='my-little-guy.png';a.href=canvas.current!.toDataURL();a.click()}}><Download size={19}/></button></div><div className="canvas-wrap"><canvas ref={canvas} width={640} height={640} aria-label="Draw your original character here using touch, mouse, or stylus. Image uploads are not accepted." onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}/>{!strokes.current.length&&<div className="canvas-hint" aria-hidden="true"><Pencil size={33}/><span>your hand. your little guy.</span><small>no uploads. no generate button.</small></div>}</div></div><div className="paint-footer"><div className="swatches">{colors.map(c=><button type="button" key={c} className={color===c?'active':''} style={{background:c}} aria-label={`Color ${c}`} aria-pressed={color===c} onClick={()=>{setColor(c);if(tool==='eraser')setTool('pen')}}/>)}</div><label className="brush-size">Size <input aria-label="Brush size" type="range" min="2" max="35" value={size} onChange={e=>setSize(+e.target.value)}/></label></div><div className="paint-status"><span>640 × 640 px · {penCount} pencil strokes</span><span>effort &gt; perfection.</span></div><div className="paint-done"><button type="button" className="primary" disabled={!penCount} onClick={()=>{stop();onDone({version:1,strokes:[...strokes.current]})}}><Check size={18}/> {doneLabel}</button><small>{doneHint}</small></div></div>
}
