import assert from 'node:assert/strict';
import nacl from 'tweetnacl';
import bs58 from 'bs58';

const base=process.env.TEST_URL||'http://127.0.0.1:5173';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('Integration fixtures may only be written to a local preview.');
async function call(path,data,cookie='',origin=base){const r=await fetch(base+'/api/'+path,{method:data===undefined?'GET':'POST',headers:{Connection:'close','Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{})},body:data===undefined?undefined:JSON.stringify(data)});const raw=await r.text();let parsed;try{parsed=JSON.parse(raw)}catch{parsed={error:raw}}return {status:r.status,data:parsed,cookie:r.headers.get('set-cookie')?.split(';')[0]}}
async function login(){const pair=nacl.sign.keyPair(),address=bs58.encode(pair.publicKey);const challenge=await call('auth/challenge',{address});assert.equal(challenge.status,200);const payload={address,nonce:challenge.data.nonce,signature:Array.from(nacl.sign.detached(new TextEncoder().encode(challenge.data.message),pair.secretKey))};const bad=await call('auth/verify',{...payload,signature:Array(64).fill(0)});assert.equal(bad.status,401);const good=await call('auth/verify',payload);assert.equal(good.status,200);assert.ok(good.cookie);assert.equal((await call('auth/verify',payload)).status,401);return {address,cookie:good.cookie}}
const drawing={version:1,strokes:[{tool:'pen',color:'#242323',size:7,points:[[100,100],[140,150],[190,170],[240,100]]},{tool:'pen',color:'#242323',size:7,points:[[150,200],[200,200],[220,240]]},{tool:'pen',color:'#8ccf6e',size:12,points:[[150,300],[200,350],[250,300]]}]};
const launchConfig=(await call('config')).data;assert.equal(launchConfig.network,'mainnet-beta');
assert.equal((await call('coins',{})).status,401);
const a=await login(),b=await login();
assert.equal((await call('coins',{},a.cookie,'https://evil.example')).status,403);
assert.equal((await call('art',{png:'garbage'},a.cookie)).status,410);
assert.equal((await call('drawings',{png:'data:image/png;base64,anything'},a.cookie)).status,400);
assert.equal((await call('drawings',{drawing:{version:1,strokes:[]}},a.cookie)).status,400);
assert.equal((await call('drawings',{drawing:{...drawing,strokes:[{...drawing.strokes[0],points:[[9999,0]]}]}},a.cookie)).status,400);
const art=await call('drawings',{drawing},a.cookie);assert.equal(art.status,201);assert.equal(art.data.source,'canvas-v1');assert.equal(art.data.drawingHash.length,64);const imageResponse=await fetch(base+art.data.url);assert.equal(imageResponse.headers.get('content-type'),'image/png');assert.ok((await imageResponse.arrayBuffer()).byteLength>100);
const coinData={name:'API test character',symbol:'TEST',description:'Local verification fixture.',pair:'SOL',image:art.data.url,communityBps:0};
assert.equal((await call('coins',coinData,b.cookie)).status,403);
assert.equal((await call('coins',{...coinData,pair:'NVDAx'},a.cookie)).status,400);
const coin=await call('coins',coinData,a.cookie);assert.equal(coin.status,201);assert.equal(coin.data.coin.owner,a.address);
const coinId=coin.data.coin.id;
assert.equal((await call('coins/'+coinId)).data.coin.name,coinData.name);
assert.equal((await call('coins/00000000-0000-4000-8000-000000000000')).status,404);
const pagePath='coins/'+coinId+'/page';
assert.equal((await call(pagePath)).data.page.revision,0);
const page={title:'the TEST clubhouse',story:'A local test drawing wall. Not a launched coin.',color:'#fff4bd',drawing,revision:0};
assert.equal((await call(pagePath,page)).status,401);
assert.equal((await call(pagePath,page,b.cookie)).status,403);
assert.equal((await call(pagePath,{...page,owner:b.address},a.cookie)).status,400);
assert.equal((await call(pagePath,{...page,color:'url(https://example.com)'},a.cookie)).status,400);
assert.equal((await call(pagePath,{...page,drawing:{version:1,strokes:[{...drawing.strokes[0],points:[[9999,0]]}]}},a.cookie)).status,400);
assert.equal((await call(pagePath,{...page,png:'data:image/png;base64,anything'},a.cookie)).status,400);
assert.equal((await call(pagePath,page,a.cookie)).data.page.revision,1);
assert.equal((await call(pagePath,page,a.cookie)).status,409);
const edited=await call(pagePath,{...page,title:'saved creator page',revision:1},a.cookie);
assert.equal(edited.status,200);assert.equal(edited.data.page.revision,2);
const persisted=(await call(pagePath)).data.page;
assert.equal(persisted.title,'saved creator page');assert.deepEqual(persisted.drawing,drawing);
assert.equal((await call(pagePath,{...page,revision:2},b.cookie)).status,403);
assert.equal((await call(pagePath)).data.page.revision,2);
const direct=await fetch(base+'/coin/'+coinId);assert.equal(direct.status,200);assert.ok((await direct.text()).includes('DOODLE'));
assert.equal((await call('coins')).data.coins.find(c=>c.id===coinId).status,'draft');
console.log('PASS: unique coin URL, public page persistence, creator-only editing, malformed drawings and uploads rejected, stale edit conflict protection.');
assert.equal((await call('coins',{...coinData,communityBps:8000},a.cookie)).status,400);
assert.deepEqual((await call('config')).data.pairs.map(p=>p.symbol),['SOL']);
const jobData={coinId:coin.data.coin.id,title:'Test a sticker pack',description:'Produce six transparent 512px PNG stickers.',reward:'0.01'};
assert.equal((await call('jobs',jobData,b.cookie)).status,403);
assert.equal((await call('jobs',{...jobData,reward:'-1'},a.cookie)).status,400);
const job=await call('jobs',jobData,a.cookie);assert.equal(job.status,201);
const work={url:'https://example.com/stickers',note:'A local test submission.'};
assert.equal((await call(`jobs/${job.data.job.id}/submit`,work,a.cookie)).status,403);
assert.equal((await call(`jobs/${job.data.job.id}/submit`,{...work,url:'javascript:alert(1)'},b.cookie)).status,400);
assert.equal((await call(`jobs/${job.data.job.id}/submit`,work,b.cookie)).status,201);
assert.equal((await call(`jobs/${job.data.job.id}/submit`,work,b.cookie)).status,409);
assert.equal((await call(`jobs/${job.data.job.id}`,undefined,b.cookie)).status,403);
const detail=await call(`jobs/${job.data.job.id}`,undefined,a.cookie);assert.equal(detail.data.job.submissions.length,1);
assert.equal((await call('launch/prepare',{coinId:coin.data.coin.id},a.cookie)).status,launchConfig.launchEnabled?400:503);
assert.equal((await call('auth/logout',{},a.cookie)).status,200);
assert.equal((await call('jobs',jobData,a.cookie)).status,401);
console.log('PASS: API checks — wallet verification, replay rejection, CSRF, ownership, stroke-only rendering, no-upload enforcement, blank-canvas rejection, artwork persistence, character/job creation, submission privacy, duplicate prevention, launch gate, logout.');
console.log('Local fixture coin: '+coin.data.coin.id);

